### ISSUE TITLE
Make apps testable without injection of InnerDriver

### ISSUE THREAD

**Issue by NickAb** [2gis/winphonedriver#44]
Visual Studio 2013 Update 2 shipped with some Coded UI support Windows Phone apps. See http://blogs.msdn.com/b/visualstudioalm/archive/2014/04/05/using-coded-ui-to-test-xaml-based-windows-phone-apps.aspx

It would be great to tap into ui automation and use it instead of inner driver, so that no modifications need in the app under a test.

**Comment by NickAb** [comment]
See https://github.com/2gis/Winium.StoreApps.CodedUi for an early prototype solution.

**Comment by Goginenni** [comment]
@NickAb Does the solution works for Silverlight apps too ?

**Comment by NickAb** [comment]
@Goginenni We developed prototype for StoreApps automation, so we did not test it against Silverlight apps.
But I have just build a simple Silverlight Pivot App and was able to print out page source and click button. Basically, **Silverlight it is supported**.

**Comment by Goginenni** [comment]
@NickAb Thank you. I will try.
