### ISSUE TITLE
Possibility to test on real devices

### ISSUE THREAD

**Issue by CAMOBAP795** [2gis/winphonedriver#45]
Hi 2GIS Team,

Is it possible to implement possibility running tests on real device in future?
Or maybe there is exists some serious barier to implement this?

Could you please explain.

By the way, Thank you for a great solution!

**Comment by NickAb** [comment]
Hello.
Testing on real device can be implemented, but there are some drawbacks.

Moreover, we are currently researching posibility of running tests on real devices and even made a prototype: https://github.com/2gis/Winium.StoreApps.CodedUi

But there are some drawbacks:
- It requires Coded UI, meaning that you have to have Visual Studio Premium or Ultimate (which are quit expensive)
- It works only for app that can be automated using Coded UI, so it is limited to XAML based apps (Store and Universal app), some Web apps. Silverlight (which is gonig to be ohased out anyway) is not supported, or it was not supported when we were looking it up.

We've also contacted [Appium](https://github.com/appium/windows-phone-8-bootstrap/issues/1) in hopes to consolidate our efforts.

**Comment by CAMOBAP795** [comment]
Thank you for clarification.
