### ISSUE TITLE
Can't send keys to PasswordBox

### ISSUE THREAD

**Issue by Goginenni** [2gis/winphonedriver#46]
Am trying to enter text to PasswordBox but couldn't succeed. send_keys function is working for TextBox but not for PasswordBox. Is there a way ?

**Comment by NickAb** [comment]
This is due to [ValueCommand.cs#L25-L31](https://github.com/2gis/winphonedriver/blob/6683e9ba896e8b8fe7801fe4bfe8e59ce22baf09/WindowsPhoneDriver/WindowsPhoneDriver.InnerDriver/Commands/ValueCommand.cs#L25-L31).

This can be fixed if PasswordBox supports IValueProvider or any other pattern.

**Comment by NickAb** [comment]
Fixed in https://github.com/2gis/winphonedriver/commit/219a2176a9a58e765c86a3dd02350868aa0fc9fb

@Goginenni Please, check if it fixed it for you.
