### ISSUE TITLE
 empty body: "application/json" for click and send_keys functions

### ISSUE THREAD

**Issue by Goginenni** [2gis/winphonedriver#47]
I am using ruby. When I perform click or send_keys methods on elements, I am getting the following error though action is succeed. it is probably due to empty response from WebDriver. 

 @driver.find_element(class:'System.Windows.Controls.TextBox').send_keys('johnander')
Selenium::WebDriver::Error::WebDriverError: empty body: "application/json" (200)

        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:58:in `create_response'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:417:in `sendKeysToElement'
        from c:/Ruby22/lib/ruby/gems/2.2.0/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/element.rb:126:in `send_keys'

**Comment by NickAb** [comment]
@Goginenni Yes, it is defiantly because of this. We used driver with python binding that do ignore empty body error and never encountered it until we forked project to make it work with StoreApps. This bug , we fixed it in Winium.StoreApps and can back-port fix to winphonedriver.

**Comment by yhtest** [comment]
We were running ruby tests in multiple machines haven't had any problems and until recently. We are installing ruby gems following the same steps on a new machine this week. We suddenly seeing this error: Selenium::WebDriver::Error::WebDriverError: empty body: "application/json" (200)
What should we do to resolve it? Thank you for your help.

**Comment by NickAb** [comment]
1. What version of driver do you use?
2. Do you version gems you install? I.e. are working machines and newly setup one has same version of selenium bindings gem?
