### ISSUE TITLE
Please release OuterDriver.exe

### ISSUE THREAD

**Issue by KonyLabs** [2gis/winphonedriver#60]
Can you please release the same like we have for winium. 

Thanks

**Comment by KonyLabs** [comment]
Ohh i see its not an active project, thats why you don't maintain like Winium. Nevermind

**Comment by NickAb** [comment]
@KonyLabs, compiled release is available for this project too https://github.com/2gis/winphonedriver/releases

**Comment by NickAb** [comment]
@KonyLabs also, we have plans to integrate both winphonedrvier and Winium.StoreApps sometime in the future, so that it will be easier to maintain both at the same level. But there is no certain date on this unfortunately.
