### ISSUE TITLE
Accessing AppMenus Buttons

### ISSUE THREAD

**Issue by KonyLabs** [2gis/winphonedriver#61]
I am not able to access AppMenu Buttons or Icons, as per my knowledge AppMenu is not the part of present(home) form just like an alert. So we don't get to see any element of AppMenu in getPageSource() output.
Any clue on how to make it work ?

**Comment by NickAb** [comment]
Current winphonedriver does not support access to AppBar items. This functionality was added in Winium.StoreApps [reference ipml](https://github.com/2gis/Winium.StoreApps/blob/master/Winium/Winium.StoreApps.InnerServer/Element/WiniumVirtualRoot.cs#L88).

Probably the easiest way would be to fix [Finder.cs](https://github.com/2gis/winphonedriver/blob/master/WindowsPhoneDriver/WindowsPhoneDriver.InnerDriver/Commands/FindByHelpers/Finder.cs#L19) to check if rootItem is visual root and if so, then add VisualTreeHelper.GetOpenPopups to iteration.

**Comment by NickAb** [comment]
But note that even if found elements in AppBar have incorrect location values, that prevents using click method to tap them. In Winium.StoreApps we had to resort to automation methods from InvokePattern

**Comment by KonyLabs** [comment]
So is there any plan to fix it ?

Thanks

**Comment by NickAb** [comment]
Yes, eventually. I can not give any deadline on this one at the moment.

**Comment by KonyLabs** [comment]
Any rough approximation ?? So that i can bug you on it after that duration.

**Comment by NickAb** [comment]
Could you remind me after 4th, maybe I will find some time.

**Comment by KonyLabs** [comment]
Yeah sure Nick. Thanks

**Comment by NickAb** [comment]
@KonyLabs, turns out I have already opened a PR #55 that makes elements from popup windows searchable back in October. But it will only make elements searchable, most likely elements from popups will have incorrect location, so it would not be possible to click them directly.

I will take a look at this PR some time later and merge it. Meanwhile you can build inner driver from the PR and see if it lets you find the elements from app bar that you wanted to find.

**Comment by KonyLabs** [comment]
@NickAb i tried with the given latest Inner Driver .... no luck , none of the appmenu is being exposed to pageSource.
Can you please look into it, its kinda urgent for me and i am blocked due to this issue.
Thanks

**Comment by NickAb** [comment]
@KonyLabs #55 adds app bar items to searchable element, but it does not fix pageSource command. 
I will fix it soon.
Meanwhile could you please try finding app bar item by its id, name or class?

**Comment by KonyLabs** [comment]
I tired with name, not searchable.

**Comment by NickAb** [comment]
Is it not searchable with InnerDriver build from #55 or from master? Also, to make it sure, app menu is items in [`phone:PhoneApplicationPage.ApplicationBar`](https://msdn.microsoft.com/en-us/library/windows/apps/hh394040(v=vs.105).aspx), is it correct?

**Comment by KonyLabs** [comment]
Yeah i tried with #55 not master. 

This is how i am creating AppMenu 
  // Sample code for building a localized ApplicationBar
        private void BuildLocalizedApplicationBar()
        {
        //    // Set the page's ApplicationBar to a new instance of ApplicationBar.
            ApplicationBar = new ApplicationBar();

        //    // Create a new button and set the text value to the localized string from AppResources.
            ApplicationBarIconButton appBarButton = new ApplicationBarIconButton(new Uri("/Assets/AppBar/appbar.add.rest.png", UriKind.Relative));
            appBarButton.Text = "menubutton";
          ApplicationBar.Buttons.Add(appBarButton);

        //    // Create a new menu item with the localized string from AppResources.
            ApplicationBarMenuItem appBarMenuItem = new ApplicationBarMenuItem(AppResources.AppBarMenuItemText);
            ApplicationBar.MenuItems.Add(appBarMenuItem);
        }

And i tried with name, not searchable.

**Comment by NickAb** [comment]
@KonyLabs what name have you tried? I don't see any Automation Name or Id being set in code sample.

I think you need to add automation name or id programmatically, like that
```
appBarButton.SetValue(AutomationProperties.AutomationIdProperty, "AddAppBarButton");
appBarMenuItem.SetValue(AutomationProperties.AutomationIdProperty, "AppBarMenuItem1");
```

**Comment by KonyLabs** [comment]
That is the problem i am facing, as Appmenu button/menu is not a dependency object so not able to set AutomationName or Id . 
And with the above suggestion, neither ApplicationBarMenuItem nor ApplicationBarIconButton contain definition of SetValue method.

**Comment by NickAb** [comment]
Will need some time to research this.

**Comment by KonyLabs** [comment]
Nick, could you please pin down this one fast ... because as i told you, i am totally blocked on automation due to this. 
Thanks

**Comment by KonyLabs** [comment]
Hi @NickAb , any update on this ?

**Comment by NickAb** [comment]
@KonyLabs, not yet, I will get back to you on Monday

**Comment by NickAb** [comment]
@KonyLabs it turns out AppBar is hard to automate as it is not a normal UI element.

I decied to go with custom ExecuteSript command. Could you please try this PR #62 

Usage:
1. In XAML or code behinde use `ClickableApplicationBarMenuItem` or/and `ClickableApplicationBarIconButton` instead of `ApplicationBarMenuItem` or/and `ApplicationBarIconButton`.

2. In your test use `ExecuteScript` command `mobile: invokeAppBarItem` with two positional arguments:
 - item type: `iconButton` if you want to invoke icon button or `menuItem` if you want to invoke menu item.
 - index: zero-based integer index of item

Python sample:
```py
        element = self.driver.find_element_by_id('MyTextBox')
        self.driver.execute_script("mobile: invokeAppBarItem", 'iconButton', 1)
        assert 'Button 2' == element.text
        self.driver.execute_script("mobile: invokeAppBarItem", 'menuItem', 0)
        assert 'MenuItem 1' == element.text
```

Xaml
```xml
    <phone:PhoneApplicationPage.ApplicationBar>
        <shell:ApplicationBar IsVisible="True" IsMenuEnabled="True">
            <public:ClickableApplicationBarIconButton Click="ClickableApplicationBarIconButton_OnClick" IconUri="/Resources/save.png" Text="Button 1"/>
            <public:ClickableApplicationBarIconButton Click="ClickableApplicationBarIconButton_OnClick" IconUri="/Resources/feature.settings.png" Text="Button 2"/>
            <shell:ApplicationBar.MenuItems>
                <public:ClickableApplicationBarMenuItem Click="ClickableApplicationBarMenuItem_OnClick"  Text="MenuItem 1"/>
                <public:ClickableApplicationBarMenuItem Click="ClickableApplicationBarMenuItem_OnClick" Text="MenuItem 2"/>
            </shell:ApplicationBar.MenuItems>
        </shell:ApplicationBar>
    </phone:PhoneApplicationPage.ApplicationBar>
```

**Comment by KonyLabs** [comment]
@NickAb , i am trying this on a sample App containing AppMenu. But it doesnt seem to work, not even able to build application. 

So i am creating App menu just like you : 
<img width="1071" alt="screen shot 2016-01-12 at 6 15 33 pm" src="https://cloud.githubusercontent.com/assets/14196612/12263935/f8762680-b958-11e5-9182-9f43f8119e45.png">

But it says, "The type 'public:ClickableApplicationBarIconButton' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built ".

I have taken the latest code. Built new Common.dll attached the same to InnerDriver preference and built the Inner driver from fresh.  Added this InnerDriver.dll 

And is it the working code, i mean you tested ? it was working for you ?

**Comment by NickAb** [comment]
Yes it was working for me. The sample app is included in source code. Checkout [appbar](https://github.com/2gis/winphonedriver/tree/appbar) branch and try building it first.

Make sure that your InnerDriver is built from appbar branch. You can open dll using ILSpy or dotPeek and verify that `ClickableApplicationBar*` classes are publicly available.
I will build outer and inner driver myself tomorrow and attach them here.

**Comment by NickAb** [comment]
@KonyLabs I think you might be missing xml namespace declaration in your XAML. I am using ReSharper that adds missing references and xmlns for me so I skipped this part.

In the top of your XAML file, right inside `phone:PhoneApplicationPage` tag add `xmlns:public="clr-namespace:WindowsPhoneDriver.InnerDriver.Public;assembly=WindowsPhoneDriver.InnerDriver"` among other xmlns declarations.

See TestApp's ManiPage.xaml for reference https://github.com/2gis/winphonedriver/blob/appbar/WindowsPhoneDriver/TestApp/MainPage.xaml#L10

**Comment by NickAb** [comment]
[WindowsPhoneDriver.OuterDriver.zip](https://github.com/2gis/winphonedriver/files/88551/WindowsPhoneDriver.OuterDriver.zip)
[WindowsPhoneDriver.InnerDriver.zip](https://github.com/2gis/winphonedriver/files/88550/WindowsPhoneDriver.InnerDriver.zip)

**Comment by NickAb** [comment]
@KonyLabs can you confirm that it works for your case?

**Comment by KonyLabs** [comment]
Yeah @NickAb , It works . But i would like to add one thing, if someone create an App menu dynamically using ClickableApplicationBarIconButton it wont work as there is no constructor defined for same. If it looks like something that has to be done then i can send PR for same. Please let me know.

**Comment by NickAb** [comment]
@KonyLabs I just checked it out, according to documentation each class should have two constructors (one default and one with uri or text parameter). I will add it myself at the start of the week.

**Comment by NickAb** [comment]
@KonyLabs I have updated PR #62, could you please confirm that it works in your case?

**Comment by KonyLabs** [comment]
Yes, did the same.Worked

**Comment by NickAb** [comment]
Changes are in the master branch now
