### ISSUE TITLE
GetSize() and  WebDriverWait . Can we have support for this two?

### ISSUE THREAD

**Issue by KonyLabs** [2gis/winphonedriver#68]
Currently it doesn't have support to get the size of an element.
And if we want to wait for an element to appear, that is also not there. 
Can you please provide support for these two ?

**Comment by NickAb** [comment]
We can back port `GetSize` from Winium.StoreApps. But I am not sure what you mean by WebDriverWait support. Waiting is implemented on client side and it should work out the box, did you get an exception while using wait? Can you provide an example to reproduce?

**Comment by KonyLabs** [comment]
Just Found Out **elementToBeClickable** wont work but **visibilityOfElementLocated** will work. I guess that would be fine for me. 
But i need getSize() functionality badly. 
And i ran into one other issue. If i execute sendKeys on password TextBox, send keys fails saying "Element referenced is not of control type". What to do in this case?

**Comment by NickAb** [comment]
Are you sure you pass correct locator? What version of driver do you use: 0.2.0 or master?

We had an issue about `PasswordBox ` and it was fixed before 0.2.0, see https://github.com/2gis/winphonedriver/issues/46

Can you reproduce it on test app with password field only or can you provide page source and driver logs?

**Comment by KonyLabs** [comment]
Yeah the locator is correct and am using 0.2.0.* driver. 
And as i am getting "Element referenced is not of control type" is error which you have modified in #46 . So i guess i am on latest branch.
The driver logs throws this : 
<img width="1202" alt="screen shot 2016-03-04 at 10 33 07 am" src="https://cloud.githubusercontent.com/assets/14196612/13518507/b1aecf94-e1f4-11e5-8977-31a1e46a177c.png">

Attaching Page Source : 
<img width="1060" alt="screen shot 2016-03-04 at 10 39 21 am" src="https://cloud.githubusercontent.com/assets/14196612/13518564/6ad39acc-e1f5-11e5-8a8a-f4ecbe70174f.png">

**Comment by KonyLabs** [comment]
One More request, can we have tapAtLocation feature through TouchAction or JavaScript Executor.

**Comment by NickAb** [comment]
The error message comes from [ValueCommand.cs#L28](https://github.com/2gis/winphonedriver/blob/ad4702af7012f39bef1250b9baa27993edfcf546/WindowsPhoneDriver/WindowsPhoneDriver.InnerDriver/Commands/ValueCommand.cs#L28) meaning that the element that you are referencing is not of a control type. Can you please provide a code of the part of test case where you locate the element?
Please do remember that the code can contain sensitive info as your are dealing with passwordbox, so make sure to replace sensitive info with some random data and marking.

**Comment by NickAb** [comment]
For `tapAtLocation` you can use move and click commands combinations. In python this can be achieved using [ActionChains](http://selenium-python.readthedocs.org/api.html#selenium.webdriver.common.action_chains.ActionChains). I am not sure if it still supported in javascript bindings.

I am referring to https://code.google.com/p/selenium/wiki/JsonWireProtocol#POST_/session/:sessionId/moveto and https://code.google.com/p/selenium/wiki/JsonWireProtocol#/session/:sessionId/click commands.

**Comment by NickAb** [comment]
@KonyLabs please try #69 for GetElementSize and GetElementRect support

**Comment by KonyLabs** [comment]
Is there any way to know the size of an Element from getPageSource() ?  If not then,how is it calculated ?

**Comment by NickAb** [comment]
No, it is not included into page source. You can ask for elements rect or size using selenium commands.
First, locate element using FindElement or FindElements, then call Size or Rect commands on element.

`element.ActualWidth` and `element.ActualHeight` are used to calculate the size.

**Comment by KonyLabs** [comment]
Yeah i am able to get Size and all but was just wondering how is it calculated or can we find it in  GetpageSource().

**Comment by NickAb** [comment]
I will add it some time later

**Comment by KonyLabs** [comment]
Regarding Gestures, i am not able to tap at location using anything. 
Your way of clicking i.e by move_to_element then click. But i don't have any element. I just want to click at particular location without any element  availaible, just like Appium and Selenium i.e TouchAction/JavaScriptExecutor.

I guess the only way left now is to perform it through JavaScript Executor ?

**Comment by NickAb** [comment]
Have you tried [move_by_offset](http://selenium-python.readthedocs.org/api.html#selenium.webdriver.common.action_chains.ActionChains.move_by_offset) from Action Chains? It does not require element and lets you move from top left corner of the screen.

In first comment in issue #67 you can see that sleekweasel uses exactly move_by to click at specified screen location, no element required.

**Comment by KonyLabs** [comment]
Yeah i tried that one too, didnt work.
<img width="653" alt="screen shot 2016-03-16 at 6 07 36 pm" src="https://cloud.githubusercontent.com/assets/14196612/13820618/2f452e7a-ebc4-11e5-83e6-1a045b0da2ea.png">


Throws **Not implemented: touchMove** , while operating move().

**Comment by NickAb** [comment]
Use Action Chain instead of Touch Actions. What langue do you use to write tests?

**Comment by KonyLabs** [comment]
I use Java. And Actions Chain is for Python i guess.

**Comment by NickAb** [comment]
Please see https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/interactions/Actions.html

Something like this should work, hopefully
```java
Actions action = new Actions(web driver);
actionmoveByOffset(x, y).click().build().perform();
```

**Comment by KonyLabs** [comment]
Actions looks helpful . Thanks :)

**Comment by KonyLabs** [comment]
Nick, when i am trying to swipe on swipable screen(Not Scrollable) . None of the command moveByOffset/Scroll is working. 
I'll provide the case : 
This is how screen looks 
<img width="321" alt="screen shot 2016-03-22 at 2 27 33 pm" src="https://cloud.githubusercontent.com/assets/14196612/13946393/54c6e8c6-f03a-11e5-90ab-7bcf891c8b37.png">

After performing swipeDown it should look like 
<img width="316" alt="screen shot 2016-03-22 at 2 27 44 pm" src="https://cloud.githubusercontent.com/assets/14196612/13946408/6acf217e-f03a-11e5-8682-d18294538562.png">

But the commands performing no swipe Operation as screens not changing on performing scroll/moveByoffset.

**Comment by NickAb** [comment]
Can you try simpler operation, like a plain click on a button first to make sure that you have actions working?

**Comment by KonyLabs** [comment]
The actions are working fine for other cases of same App. Its just the swipe which is not working.

**Comment by NickAb** [comment]
If you still experience problems with swiping, please open a new issue, preferable with minimal test app to reproduce. Because we used swiping in our app, that we test, without problems.
