### ISSUE TITLE
Rotating Screen as Landscape and Potrait

### ISSUE THREAD

**Issue by KonyLabs** [2gis/winphonedriver#71]
I was trying to implement orientation to Landscape/portrait by implementing Rotatable interface to WindowsPhoneDriver. Not having any luck.

**Comment by NickAb** [comment]
Orientation commands are not implemented in this version of driver. You can try backporting it from Winium.StoreApps https://github.com/2gis/Winium.StoreApps/blob/efb0b81ea01243d898fcba88f99ca7513b7925ac/Winium/Winium.StoreApps.Driver/CommandExecutors/SetOrientationExecutor.cs

**Comment by NickAb** [comment]
Rotation should work in Winium.Mobile
