### ISSUE TITLE
Scroll feature is not working using executescript()

### ISSUE THREAD

**Issue by gouthamsam** [2gis/winphonedriver#83]
Unknown 'mobile:' script command. See https://github.com/2gis/winphonedriver/wiki/Command-Execute-Script for supported commands
getAppiumDriver().executeScript("mobile: scroll", scrollObject);

Thanks

**Comment by NickAb** [comment]
It is Appium specific executeScript command that is not implemented in winphonedriver.

If you want this command implemented, please file an issue at https://github.com/2gis/Winium.Mobile.

We merged windowsphonedriver and Winium.StoreApps projects, any further development will be made in Winium.Mobile repo, this repo is discontinued.

**Comment by NickAb** [comment]
See Winium.Mobile release https://github.com/2gis/Winium.Mobile/releases/tag/v1.7.1

Here is docs on how to use `ExecuteScript` to scroll and more https://github.com/2gis/Winium.Mobile/wiki/Command-Execute-Script

```py
list_box = self.driver.find_element_by_id("ListBox")
scroll_info = {"v": "smallIncrement", "count": 10}
self.driver.execute_script("automation: ScrollPattern.Scroll", list_box, scroll_info)
```
